### ISSUE TITLE
ModuleNotFound: quo

### ISSUE THREAD

**Issue by fxckinsa1int** [scalabli/sashay#7]
![Снимок экрана (381)](https://user-images.githubusercontent.com/100631012/156403367-4140dc8f-d13b-499b-a149-2fd25655b6d8.png)

**Comment by fxckinsa1int** [comment]
> Your system is failing to download quo but the module is specified in the **requirements.txt** file. Kindly install quo manually.
> 
> `pip install -U quo`

i already tried, and i have it already installed, but it doesn't work

**Comment by fxckinsa1int** [comment]
![Снимок экрана (382)](https://user-images.githubusercontent.com/100631012/156729703-8ea258cb-cc2d-440c-869c-c178aaf8b65d.png)

**Comment by Elforget** [comment]
Same error, installed manually and nothing works. Is there a solution to this problem?

**Comment by gerrishons** [comment]
@Elforget what python version are you using?
And what's your OS?

Sashay works with ``python3. 8`` and newer versions...

**Comment by gerrishons** [comment]
@Elforget and @fxckinsa1int 

There are often multiple versions of python interpreters and pip versions present in your system, to solve this we've dropped support for python2, the requirement files were being installed on python2 but sashay uses python3
Also sashay works best when your in root

Kindly reclone the repo and check if the problem has been resolved.
